### ISSUE TITLE
Payengine compatibility information

### ISSUE THREAD

**Issue by amer8** [concardis/Docs#113]
If understood correctly, the REST API isn't compatible with every version of the Payengine, therefore a short info or a compatibility table would be helpful.

**Comment by ConcardisECCC** [comment]
Hi @amer8 ,
what exactly do you mean with "the REST API isn't compatible with every version of the Payengine". I guess you are talking about different Payengine products / platforms which unfortunately are all named Payengine, right?

**Comment by amer8** [comment]
Hi @ConcardisECCC, yes it seems that are different platforms/versions/products.
When i called the Concardis technical support and was interested into migrating from DirectLink to REST API, the response was that the REST API isn't compatible with the subscribed Payengine version. Sounds like it has been introduced later or it is a paid add-on.
I wish i would have found the information in the docs without contacting the support.
